### ISSUE TITLE
Don't use CPP

### ISSUE THREAD

**Issue by Kritzefitz** [haskell-hvr/hgettext#13]
Preprocessing Haskell files with CPP can in some cases break Haskell syntax. For example multi line string literals like the following break. Even though they are valid Haskell.

    foo = "abc\
          \def"

I think the most idiomatic way to replace CPP would be to auto-generate a module, similar to what Cabal already does with `Paths_<pkg>`.

Not using CPP in future versions would suddenly break compatibility, so this should probably be controllable via a flag in *.cabal.

Would you be open for merge requests in this direction?

**Comment by hvr** [comment]
I'm generally sympathetic to reducing CPP usage. Can you elaborate a bit more concretely the logic to use instead of CPP? (and btw, we don't need any flags; we'd simply use a major version increment to signal a backward compat change).

**Comment by Kritzefitz** [comment]
my idea is to add a `preBuild` hook that generates a module with a name something like `Paths_hgettext_<pkg>` (similar to what [`Distribution.Simple.Build.PathsModule.generate`](http://hackage.haskell.org/package/Cabal-2.2.0.1/docs/Distribution-Simple-Build-PathsModule.html#v:generate) does). The module will contain the definitions for `messageCatalogDomain :: String` and `messageCatalogDir :: FilePath`. When building the generated module is compiled along with the rest of the package and may be imported by the user when needed.

As [described in the Cabal user guide](https://www.haskell.org/cabal/users-guide/developing-packages.html#autogenerated-modules) the user would have to add the module to their `other-modules` and `autogen-modules`, similar to what is already necessary for the [`Paths_<pkg>`](https://www.haskell.org/cabal/users-guide/developing-packages.html#accessing-data-files-from-package-code) module generated by Cabal itself.

**Comment by andreasabel** [comment]
Is there still interest in this issue?

(Note that the cabal developers want to move away from custom build scripts in the long run...)

**Comment by Kritzefitz** [comment]
Not really. Since the situation hasn't change since the issue was opened, I believe someone may still run across this problem in the wild. But personally I haven't used hgettext in a long time and can't really claim to have a strong interest in this issue.

**Comment by andreasabel** [comment]
Thanks, @Kritzefitz, for the feedback.  I am closing this then.  We shall see whether it comes back.
