### ISSUE TITLE
Build fails with Cabal 2.4

### ISSUE THREAD

**Issue by jtojnar** [haskell-hvr/hgettext#15]
[`matchFileGlob`](https://www.stackage.org/haddock/lts-10.9/Cabal-2.0.1.1/Distribution-Simple-Utils.html#g:10) was removed in 2.4 (https://github.com/haskell/cabal/pull/5284) and [`Distribution.Simple.Glob.matchDirFileGlob`](https://www.stackage.org/haddock/lts-13.9/Cabal-2.4.1.0/Distribution-Simple-Glob.html#v:matchDirFileGlob) with widely different type is supposed to be used instead.

I am not really sure where are we supposed to get the `PackageDescription` argument value. Perhaps something like https://github.com/google/proto-lens/pull/242/files#diff-4fe9daabe5a3a972435eb21087de0259R183 could work.

**Comment by ag-eitilt** [comment]
Once one fix or another for this is finalized, this issue is also blocking bumps to GHC 8.8/`base ==4.13.*` and `containers ==0.6.*`; it'll probably be a good idea to see if the code builds with those versions afterward and adapt the bounds appropriately.
