### ISSUE TITLE
Maintainer wanted

### ISSUE THREAD

**Issue by andreasabel** [haskell-hvr/hgettext#25]
This is a stable package which I just updated to GHC 9.8 (just bumping upper bounds of dependencies).

@NH002 Looking at the reverse dependencies (3), you stood out as an active user of this package.  Would you take over this package?  I am not using it myself.

**Comment by NH002** [comment]
@andreasabel Yes, I want to to take over maintainence of this package.

**Comment by andreasabel** [comment]
Great!  I invited you to this repo with write access and added you to the Hackage uploaders for this package:
https://hackage.haskell.org/package/hgettext/maintainers/

**Comment by NH002** [comment]
Thanks, and I have accepted your invitation.

**Comment by andreasabel** [comment]
Thanks, Nikola!
