### ISSUE TITLE
TemplateHaskell extension not used

### ISSUE THREAD

**Issue by Kritzefitz** [haskell-hvr/hgettext#9]
hgettext.cabal lists `TemplateHaskell` as an extension for the hgettext executable. hgettext.hs doesn't seem to actually use TemplateHaskell (as an extension) and in Debian we actually compile hgettext with that line removed from hgettext.cabal.
Is there some specific reason to list it as an extension in hgettext.cabal?

**Comment by hvr** [comment]
The extension was removed via #6
